# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = erase, py39, py310, py311, py312, py313, report

[testenv:erase]
skip_install = True
deps = coverage
commands = coverage erase

[testenv:report]
skip_install = True
deps = coverage
commands =
    - coverage html
    - coverage report -m

[testenv]
extras = dev
commands = pytest --cov=talkey --cov-append {posargs}
